### ISSUE TITLE
Error with initial_clean and sudo

### ISSUE THREAD

**Issue by milliams** [oVirt/ovirt-ansible-hosted-engine-setup#143]
In `tasks/initial_clean.yml` there is, at the end a task:

```yaml
  - name: Remove eventually entries for the local VM from known_hosts file
    known_hosts:
      name: "{{ he_fqdn }}"
      state: absent
    delegate_to: localhost
```

This causes an error of:

```yaml
fatal: [foo.example.com -> localhost]: FAILED! => changed=false 
  module_stderr: |-
    sudo: a password is required
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

since it is trying to `sudo` up on the local machine running Ansible since we have, in our playbook:

```yaml
  become: True
  become_user: root
```

I think that the task could do with a `become: no`.

If you agree with this issue and would like, I can put a PR together?
